export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SAVE_INGREDIENTS = 'SAVE_INGREDIENTS';
export const SIGN_TO_ORDER = 'SIGN_TO_ORDER';
export const RESET_SIGN_TO_ORDER = 'RESET_SIGN_TO_ORDER';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';
export const SAVE_ERROR = 'SAVE_ERROR';

export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAIL = 'PURCHASE_FAIL';
export const PURCHASE_START = 'PURCHASE_START';
export const PURCHASE_INITIALIZER = 'PURCHASE_INITIALIZER';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const REGISTER_FAILED = 'REGISTER_FAILED';